--------------------------------------------- DDL STATEMENTS -------------------------------------------

-- CREATE STATEMENTS

CREATE TABLE CATEGORY (
    CategoryID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryName VARCHAR2(100) NOT NULL,
    Description CLOB
);

CREATE TABLE CUSTOMER (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(255) NOT NULL,
    RegistrationDate DATE DEFAULT SYSDATE
);

CREATE TABLE PRODUCT (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CategoryID NUMBER,
    ProductName VARCHAR2(100) NOT NULL,
    Description CLOB,
    Price NUMBER(10, 2) NOT NULL,
    StockQuantity NUMBER DEFAULT 0,
    CONSTRAINT fk_prod_cat FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE SET NULL
);

CREATE TABLE ORDERS (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerID NUMBER NOT NULL,
    OrderDate DATE DEFAULT SYSDATE,
    TotalAmount NUMBER(10, 2) NOT NULL,
    Status VARCHAR2(20) DEFAULT 'Pending',
    CONSTRAINT fk_ord_cust FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID) ON DELETE CASCADE
);

CREATE TABLE ORDER_DETAIL (
    OrderDetailID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL,
    ProductID NUMBER NOT NULL,
    Quantity NUMBER NOT NULL,
    UnitPrice NUMBER(10, 2) NOT NULL,
    CONSTRAINT fk_od_order FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE,
    CONSTRAINT fk_od_prod FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID) ON DELETE CASCADE
);

CREATE TABLE SHIPPING (
    ShippingID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL UNIQUE,
    TrackingNumber VARCHAR2(50) UNIQUE,
    Carrier VARCHAR2(50),
    EstimatedDeliveryDate DATE,
    Status VARCHAR2(20) DEFAULT 'Processing',
    CONSTRAINT fk_ship_ord FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE
);

CREATE TABLE PAYMENT (
    PaymentID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    OrderID NUMBER NOT NULL UNIQUE,
    Amount NUMBER(10, 2) NOT NULL,
    PaymentDate DATE DEFAULT SYSDATE,
    PaymentType VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_pay_ord FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID) ON DELETE CASCADE
);

CREATE TABLE CARD_PAYMENT (
    PaymentID NUMBER PRIMARY KEY,
    CardHolderName VARCHAR2(100) NOT NULL,
    LastFourDigits CHAR(4) NOT NULL,
    ExpirationMonth NUMBER NOT NULL,
    ExpirationYear NUMBER NOT NULL,
    CONSTRAINT fk_card_pay FOREIGN KEY (PaymentID) REFERENCES PAYMENT(PaymentID) ON DELETE CASCADE
);

-- INSERT STATEMENTS

INSERT INTO CATEGORY (CategoryName, Description) VALUES ('Classic Cloaks', 'Cotton and bamboo wraps.');
INSERT INTO CATEGORY (CategoryName, Description) VALUES ('Premium Cloaks', 'High-end silk and thermal fleece.');

INSERT INTO CUSTOMER (FirstName, LastName, Email, PasswordHash) VALUES ('Roger', 'Federer', 'roger@federer.com', 'hashed123');
INSERT INTO CUSTOMER (FirstName, LastName, Email, PasswordHash) VALUES ('Rapahel', 'Nadal', 'raph@nadal.com', 'hashed456');

INSERT INTO PRODUCT (CategoryID, ProductName, Description, Price, StockQuantity) VALUES (1, 'Zen Cotton Cloak', '100% organic cotton.', 45.00, 50);
INSERT INTO PRODUCT (CategoryID, ProductName, Description, Price, StockQuantity) VALUES (1, 'Bamboo Wrap', 'Eco-friendly bamboo.', 60.00, 30);
INSERT INTO PRODUCT (CategoryID, ProductName, Description, Price, StockQuantity) VALUES (2, 'Thermal Lotus Cloak', 'Fleece-lined.', 85.00, 20);
INSERT INTO PRODUCT (CategoryID, ProductName, Description, Price, StockQuantity) VALUES (2, 'Midnight Silk Cloak', 'Premium midnight blue silk.', 110.00, 10);

INSERT INTO ORDERS (CustomerID, TotalAmount, Status) VALUES (1, 155.00, 'Processing');
INSERT INTO ORDERS (CustomerID, TotalAmount, Status) VALUES (2, 60.00, 'Shipped');

INSERT INTO ORDER_DETAIL (OrderID, ProductID, Quantity, UnitPrice) VALUES (1, 1, 1, 45.00);
INSERT INTO ORDER_DETAIL (OrderID, ProductID, Quantity, UnitPrice) VALUES (1, 4, 1, 110.00);
INSERT INTO ORDER_DETAIL (OrderID, ProductID, Quantity, UnitPrice) VALUES (2, 2, 1, 60.00);

-- ALTER

ALTER TABLE PRODUCT ADD ImageURL VARCHAR(255) DEFAULT 'assets/img/placeholder.jpg';

-------------------------------------------------- DML STATEMENTS ------------------------------------------------

-- JOIN
SELECT p.ProductName, c.CategoryName, p.Price
FROM PRODUCT p
JOIN CATEGORY c ON p.CategoryID = c.CategoryID;

-- SUBQUERY
SELECT ProductName, Price
FROM PRODUCT
WHERE Price > (SELECT AVG(Price) FROM PRODUCT);

-- GROUP BY
SELECT c.CategoryName, COUNT(p.ProductID) AS TotalProducts
FROM CATEGORY c
LEFT JOIN PRODUCT p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryName;

-- DATE FUNCTION
SELECT OrderID, TotalAmount, TO_CHAR(OrderDate, 'Month YYYY') AS FormattedDate
FROM ORDERS;

-- CHAR FUNCTION
SELECT UPPER(LastName) || ', ' || FirstName AS FormattedName, Email
FROM CUSTOMER;

-- UPDATE
UPDATE PRODUCT SET ImageURL = 'assets/img/zen.jpg' WHERE ProductID = 1;

UPDATE PRODUCT SET ImageURL = 'assets/img/bamboo.jpg' WHERE ProductID = 2;

UPDATE PRODUCT SET ImageURL = 'assets/img/thermal.jpg' WHERE ProductID = 3;

UPDATE PRODUCT SET ImageURL = 'assets/img/silk.jpg' WHERE ProductID = 4;